# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aces < Formula
  desc "Encode in a character set of your choice"
  homepage "https://github.com/quackduck/aces"
  version "1.0.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/aces/releases/download/v1.0.0/aces_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "ffc3f18e4844760a3423424da408212b33fa76b351749b3967e4913368c99291"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/aces/releases/download/v1.0.0/aces_1.0.0_Linux_x86_64.tar.gz"
      sha256 "949bd27b5c66074de66d0346cfd66caeae224e9fece21bfaf404c2f7eea5b870"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/aces/releases/download/v1.0.0/aces_1.0.0_Linux_armv6.tar.gz"
      sha256 "9ba085760ae3ba02c85718e7c321e9c22bca59eae953b8ec11542dbabc8c1200"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/aces/releases/download/v1.0.0/aces_1.0.0_Linux_arm64.tar.gz"
      sha256 "0183df9c6632a308177c95b6c3d5b2be52125d9773f97edc0d3cf0273fe0b202"
    end
  end

  def install
    bin.install "aces"
  end
end
