# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aces < Formula
  desc "Encode in a character set of your choice"
  homepage "https://github.com/quackduck/aces"
  version "2.2.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/aces/releases/download/v2.2.10/aces_Darwin_x86_64.tar.gz"
      sha256 "0ebab4fc82836d06a4ffbe345265784bd2ffac7bb5c0450ca50c8b8b3214066d"

      def install
        bin.install "aces"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quackduck/aces/releases/download/v2.2.10/aces_Darwin_arm64.tar.gz"
      sha256 "1177e6c7e9122b1380d31f8edce467066670de4e9efbcc50afd3e59c57b58dea"

      def install
        bin.install "aces"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/aces/releases/download/v2.2.10/aces_Linux_x86_64.tar.gz"
      sha256 "4b601fc420bc82906f45ff1109ba8453fc805d7f0d36a8ef82b63f92483415b4"

      def install
        bin.install "aces"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/aces/releases/download/v2.2.10/aces_Linux_arm64.tar.gz"
      sha256 "10e8faa24f4f4f689f83d1b7f2284b248d22fa3b659439c570a9f80bf5617fe7"

      def install
        bin.install "aces"
      end
    end
  end
end
