# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cool < Formula
  desc "Never let kernel_task eat up CPU again."
  homepage "https://github.com/quackduck/cool"
  version "0.1.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/quackduck/cool/releases/download/v0.1.1/cool_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "624028bc214ea106e305a28446c05dadab28b9cf9e9089561733907fc39bc3cd"
  end

  def install
    bin.install "tii" "smc"
  end
end
