# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dl < Formula
  desc "Print, download or copy website content"
  homepage "https://github.com/quackduck/dl"
  version "1.0.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/quackduck/dl/releases/download/v1.0.0/dl_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "d627442f108e34ece92876f56ff0f88afe72fcf6a0d30438957020c190184caf"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/quackduck/dl/releases/download/v1.0.0/dl_1.0.0_Linux_x86_64.tar.gz"
    sha256 "68ee00391487e6fcc885ba6d13edcf5ab866a67e85acc7ab8d6fff71664d19b5"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/quackduck/dl/releases/download/v1.0.0/dl_1.0.0_Linux_armv6.tar.gz"
    sha256 "f799ddf30120629bfdfa079ef793c09ccb06412b3182d96c5f09f204362ebd18"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/quackduck/dl/releases/download/v1.0.0/dl_1.0.0_Linux_arm64.tar.gz"
    sha256 "43574576c5a8d6dbe4e69ad2da26cd604904340846d97989e94b1748c95ac8ee"
  end

  def install
    bin.install "dl"
  end
end
