# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ncis < Formula
  desc "Brute force ssh easily"
  homepage "https://github.com/quackduck/ncis"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/quackduck/ncis/releases/download/v1.0.1/ncis_1.0.1_Darwin_x86_64.tar.gz"
    sha256 "c7baf1e0fe5205b9a489c96fc5a05f136ddbc73e0c2ffc093a88a74459ca5cd4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/quackduck/ncis/releases/download/v1.0.1/ncis_1.0.1_Linux_x86_64.tar.gz"
    sha256 "c7ccac4f0efc151f9a73ee78d1d53e1747678cd85d9874245bd88511690e2336"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/quackduck/ncis/releases/download/v1.0.1/ncis_1.0.1_Linux_armv6.tar.gz"
    sha256 "88905d37d5558b7d7d182e2adbf9e9cd54fb0c42af4f127a699b5054d335489a"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/quackduck/ncis/releases/download/v1.0.1/ncis_1.0.1_Linux_arm64.tar.gz"
    sha256 "46b467c86bd5d5751cc0000af5eee99b4b4644c93fb298cfd977a135b28dd54c"
  end

  def install
    bin.install "ncis"
  end
end
