# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ncis < Formula
  desc "Brute force ssh easily"
  homepage "https://github.com/quackduck/ncis"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quackduck/ncis/releases/download/v1.0.2/ncis_1.0.2_Darwin_arm64.tar.gz"
      sha256 "5dda13c96a2839eb2567a1aaa7d9964438d937e4451f520cf45ad7a732b5cf51"

      def install
        bin.install "ncis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/ncis/releases/download/v1.0.2/ncis_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "f8dbb8f135c96bd4018601e4b5383a5aea0b2e8d008fa0e1bc0a06fc00419ba9"

      def install
        bin.install "ncis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/ncis/releases/download/v1.0.2/ncis_1.0.2_Linux_armv6.tar.gz"
      sha256 "59e19e178c2acea827b301e27a05d293ab2e8a18f32a3b1464813cafc2519f59"

      def install
        bin.install "ncis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/ncis/releases/download/v1.0.2/ncis_1.0.2_Linux_x86_64.tar.gz"
      sha256 "a31eeb860f1e265fec01d5a6796ec5e31d793d306df7aa5cf4c5e8b82ad355f2"

      def install
        bin.install "ncis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/ncis/releases/download/v1.0.2/ncis_1.0.2_Linux_arm64.tar.gz"
      sha256 "d4e58ddf18349ac6b0eea4a676decd2c51a2b848508413a7c064e5fb13d60dec"

      def install
        bin.install "ncis"
      end
    end
  end
end
