# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rem < Formula
  desc "Rem is a CLI Trash which makes it ridiculously easy to recover them."
  homepage "https://github.com/quackduck/rem"
  version "2.3.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/rem/releases/download/v2.3.6/rem_2.3.6_Darwin_x86_64.tar.gz"
      sha256 "711797efd383cc9f2b5cfa50eabe9ba7eb19c84a76506857bc2f4b8445f0816a"

      def install
        bin.install "rem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quackduck/rem/releases/download/v2.3.6/rem_2.3.6_Darwin_arm64.tar.gz"
      sha256 "17c3052e12974b7868ae53092fef22ed15feb49997be6cb7a3c712a554821dc5"

      def install
        bin.install "rem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/rem/releases/download/v2.3.6/rem_2.3.6_Linux_armv6.tar.gz"
      sha256 "37cb4e7890a6503f5c79e2df882893ab9170d6de5e514d39f37ac991f0059306"

      def install
        bin.install "rem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/rem/releases/download/v2.3.6/rem_2.3.6_Linux_x86_64.tar.gz"
      sha256 "35a3202e9331974b07ea3cfdc8ff7d8579884ad7f6d31d69e438b2120b746192"

      def install
        bin.install "rem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/rem/releases/download/v2.3.6/rem_2.3.6_Linux_arm64.tar.gz"
      sha256 "b0893c3310bace15c077c56e918dcb2e544234bdb933478180e3269f634111d7"

      def install
        bin.install "rem"
      end
    end
  end
end
