# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secret < Formula
  desc "Encrypt anything with a password"
  homepage "https://github.com/quackduck/secret"
  version "1.0.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/quackduck/secret/releases/download/v1.0.0/secret_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "c9625b032d6d5706c01c5576643fb98beca8cfad3342d45a89d02798315e3ddc"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/quackduck/secret/releases/download/v1.0.0/secret_1.0.0_Linux_x86_64.tar.gz"
    sha256 "b3ce06c44827b4bfb5071a1dd45e8f949bf3c441b7f2affc76b8ddc53e32bc5d"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/quackduck/secret/releases/download/v1.0.0/secret_1.0.0_Linux_armv6.tar.gz"
    sha256 "b36952b3034e0df05d80ffad1eeebe8c9e18e77c69a9a1ffbbf9f6f38a923b2a"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/quackduck/secret/releases/download/v1.0.0/secret_1.0.0_Linux_arm64.tar.gz"
    sha256 "4d8a23b72cab9e4dfaba6e3cf450411acc59f97a4a8db39fffab5340369add25"
  end

  def install
    bin.install "cool"
    bin.install "smc"
  end
end
