# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shamoji < Formula
  desc "All the security of SHA256 in 26 emoji"
  homepage "https://github.com/quackduck/shamoji"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quackduck/shamoji/releases/download/v1.0.0/shamoji_1.0.0_Darwin_arm64.tar.gz"
      sha256 "35fb1537dc00f13eb73414ac169ddcc1cc0efa781aa6d218a69009f17ebca8c9"

      def install
        bin.install "shamoji"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/shamoji/releases/download/v1.0.0/shamoji_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "704688c8d1fba78bd1f3bc6481c3a94503ecfd951a3f33909fa77202db5a022c"

      def install
        bin.install "shamoji"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/shamoji/releases/download/v1.0.0/shamoji_1.0.0_Linux_armv6.tar.gz"
      sha256 "70c03d76b59ec2c6afb2c883545d49b969af544a2839eafb923e94c7c30aa7f0"

      def install
        bin.install "shamoji"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/shamoji/releases/download/v1.0.0/shamoji_1.0.0_Linux_x86_64.tar.gz"
      sha256 "9db5d1d1d2d80c2aa18731284b8f43d213c2c72cb430270d34fc04783c89fdfe"

      def install
        bin.install "shamoji"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/shamoji/releases/download/v1.0.0/shamoji_1.0.0_Linux_arm64.tar.gz"
      sha256 "af8af2ce3684d0438390c066b413936d5fda5bf2aa0be7ba2fb14afee1de44e3"

      def install
        bin.install "shamoji"
      end
    end
  end
end
