# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tarzan < Formula
  desc "Cross-platform shared clipboard"
  homepage "https://github.com/quackduck/tarzan"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quackduck/tarzan/releases/download/v0.1.1/tarzan_0.1.1_Darwin_arm64.tar.gz"
      sha256 "8a4cc8d0430915a72053569020ae81430ddbe1221e0709d6028b3f6181eb2486"

      def install
        bin.install "tarzan"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/tarzan/releases/download/v0.1.1/tarzan_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "62e0fc24a77c6e6cc35653f3e8c30d34e763991e85c5fea067fdc8a5a0558d9e"

      def install
        bin.install "tarzan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/tarzan/releases/download/v0.1.1/tarzan_0.1.1_Linux_armv6.tar.gz"
      sha256 "fda363183ff87b8011593686f23d575ce91dd247bb16516b6a4f9279d02e1f4f"

      def install
        bin.install "tarzan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/tarzan/releases/download/v0.1.1/tarzan_0.1.1_Linux_arm64.tar.gz"
      sha256 "d78be6d3cbeaf489be03f9b934f3e33f0b90a7578eeeb077bc906f5589bee4bf"

      def install
        bin.install "tarzan"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/tarzan/releases/download/v0.1.1/tarzan_0.1.1_Linux_x86_64.tar.gz"
      sha256 "6b4dbc732ee1c3eb710d8a8ab7fec38c74d313016d17a850aeb98d151708c2d2"

      def install
        bin.install "tarzan"
      end
    end
  end
end
