# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tii < Formula
  desc "Command not found? Install it right there!"
  homepage "https://github.com/quackduck/tii"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/tii/releases/download/v1.0.7/tii_1.0.7_Darwin_x86_64.tar.gz"
      sha256 "caff616d322749ddba940cf2e03991bc92808aedece88850cfba9b8502793384"

      def install
        bin.install "tii"
        fish_function.install "shell/tii_on_command_not_found.fish"
        (prefix/"etc/profile.d").install "shell/tii_on_command_not_found.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quackduck/tii/releases/download/v1.0.7/tii_1.0.7_Darwin_arm64.tar.gz"
      sha256 "87c766b0012894562f884eab177e608cc629d7521fbb14a8d94466c4836105da"

      def install
        bin.install "tii"
        fish_function.install "shell/tii_on_command_not_found.fish"
        (prefix/"etc/profile.d").install "shell/tii_on_command_not_found.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/tii/releases/download/v1.0.7/tii_1.0.7_Linux_armv6.tar.gz"
      sha256 "35c80bfccd8d70c09b752e3947c1a0f30e5fe3236f30f84dee3f88170603fd12"

      def install
        bin.install "tii"
        fish_function.install "shell/tii_on_command_not_found.fish"
        (prefix/"etc/profile.d").install "shell/tii_on_command_not_found.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/tii/releases/download/v1.0.7/tii_1.0.7_Linux_arm64.tar.gz"
      sha256 "f7886ea2b98b05752ce27c4c444d5f204e45238f5b7d2a53bd4d658d54bc20b7"

      def install
        bin.install "tii"
        fish_function.install "shell/tii_on_command_not_found.fish"
        (prefix/"etc/profile.d").install "shell/tii_on_command_not_found.sh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/tii/releases/download/v1.0.7/tii_1.0.7_Linux_x86_64.tar.gz"
      sha256 "aaeb056c14297d95c17df3c078a77c654e44e8f6d9515fef6d1627ece19aed39"

      def install
        bin.install "tii"
        fish_function.install "shell/tii_on_command_not_found.fish"
        (prefix/"etc/profile.d").install "shell/tii_on_command_not_found.sh"
      end
    end
  end

  def caveats; <<~EOS
    For bash or zsh, put something like this in a profile file (like ~/.bash_profile or ~/.zshrc):
    . #{etc}/profile.d/tii_on_command_not_found.sh
  EOS
  end
end
