# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tii < Formula
  desc "Command not found? Install it right there!"
  homepage "https://github.com/quackduck/tii"
  version "2.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quackduck/tii/releases/download/v2.0.0/tii_2.0.0_Darwin_arm64.tar.gz"
      sha256 "93bd5cbb81ab8c6a64a8177024049d40736599862a7e516669c5a95850b212b8"

      def install
        bin.install "tii"
        fish_function.install "shell/__fish_command_not_found_handler.fish"
        (prefix/"etc/profile.d").install "shell/tii_on_command_not_found.sh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/tii/releases/download/v2.0.0/tii_2.0.0_Darwin_x86_64.tar.gz"
      sha256 "08d133bb24f94ce2d6e18b22e3bfa35e413cab89cf28236af1d6f1a251985f9a"

      def install
        bin.install "tii"
        fish_function.install "shell/__fish_command_not_found_handler.fish"
        (prefix/"etc/profile.d").install "shell/tii_on_command_not_found.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/tii/releases/download/v2.0.0/tii_2.0.0_Linux_x86_64.tar.gz"
      sha256 "246cd9bd8ecea419dfe37d9130a1c4238721a6ab3df59a7938a8a20cd62dc14f"

      def install
        bin.install "tii"
        fish_function.install "shell/__fish_command_not_found_handler.fish"
        (prefix/"etc/profile.d").install "shell/tii_on_command_not_found.sh"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/tii/releases/download/v2.0.0/tii_2.0.0_Linux_armv6.tar.gz"
      sha256 "56c0ad4b6a87895a1fced843eb702f99741bc8227b28b04a7f7dbc915f94e4db"

      def install
        bin.install "tii"
        fish_function.install "shell/__fish_command_not_found_handler.fish"
        (prefix/"etc/profile.d").install "shell/tii_on_command_not_found.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/tii/releases/download/v2.0.0/tii_2.0.0_Linux_arm64.tar.gz"
      sha256 "b0be660506b54a6276495fba4f9173c8e10ed422ceaed947d8fe29beb9cc6a49"

      def install
        bin.install "tii"
        fish_function.install "shell/__fish_command_not_found_handler.fish"
        (prefix/"etc/profile.d").install "shell/tii_on_command_not_found.sh"
      end
    end
  end

  def caveats
    <<~EOS
      For bash or zsh, put something like this in a profile file (like ~/.bash_profile or ~/.zshrc):
      . #{etc}/profile.d/tii_on_command_not_found.sh
    EOS
  end
end
