# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uniclip < Formula
  desc "Cross-platform shared clipboard"
  homepage "https://github.com/quackduck/uniclip"
  version "2.3.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quackduck/uniclip/releases/download/v2.3.3/uniclip_2.3.3_Darwin_arm64.tar.gz"
      sha256 "8536a99098cebb2f92585a07e491a12ba543fd552ae6101cfc6bbf00fb59d44b"

      def install
        bin.install "uniclip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/uniclip/releases/download/v2.3.3/uniclip_2.3.3_Darwin_x86_64.tar.gz"
      sha256 "df5ee73d0e59a1c01217d34cb738d797f658788e89f52ceef1e54450416839c8"

      def install
        bin.install "uniclip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/uniclip/releases/download/v2.3.3/uniclip_2.3.3_Linux_armv6.tar.gz"
      sha256 "28f3ba2a1d85ef505953dbfdce04b88cc638ce865b16eeea15f09d89b3ccb5dc"

      def install
        bin.install "uniclip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/uniclip/releases/download/v2.3.3/uniclip_2.3.3_Linux_arm64.tar.gz"
      sha256 "2838ccf54201265afa17323b1f0d9b6b0114268a7bb48ae2109a725909fe9954"

      def install
        bin.install "uniclip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/uniclip/releases/download/v2.3.3/uniclip_2.3.3_Linux_x86_64.tar.gz"
      sha256 "d6fdd2443b25e34fccbdbf5e9479ef964136106e1229ab691f824fc1365d2975"

      def install
        bin.install "uniclip"
      end
    end
  end
end
