# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WdGo < Formula
  desc "Warp across the filesystem instantly"
  homepage "https://github.com/quackduck/warpdrive-go"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quackduck/warpdrive-go/releases/download/v1.0.4/wd-go_1.0.4_Darwin_arm64.tar.gz"
      sha256 "b8e2d28418733f3e8029fe09d14b7cd28ac93520993fda8da77d77f7ab299835"

      def install
        bin.install "wd-go"
        fish_function.install "fish-support/wd.fish"
        (share/"fish/vendor_conf.d").install "fish-support/wd-go_on_prompt.fish"
        (prefix/"etc/profile.d").install "bash-zsh-support/wd.sh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/warpdrive-go/releases/download/v1.0.4/wd-go_1.0.4_Darwin_x86_64.tar.gz"
      sha256 "76c44165065a2408330171d9efc860a631f1a40ad165a10f262be47edde4a6fb"

      def install
        bin.install "wd-go"
        fish_function.install "fish-support/wd.fish"
        (share/"fish/vendor_conf.d").install "fish-support/wd-go_on_prompt.fish"
        (prefix/"etc/profile.d").install "bash-zsh-support/wd.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/warpdrive-go/releases/download/v1.0.4/wd-go_1.0.4_Linux_armv6.tar.gz"
      sha256 "e04c276f501f0e9620f0d3796516eef26fba1f79ea3c1c1020210e23efa94ec9"

      def install
        bin.install "wd-go"
        fish_function.install "fish-support/wd.fish"
        (share/"fish/vendor_conf.d").install "fish-support/wd-go_on_prompt.fish"
        (prefix/"etc/profile.d").install "bash-zsh-support/wd.sh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/warpdrive-go/releases/download/v1.0.4/wd-go_1.0.4_Linux_x86_64.tar.gz"
      sha256 "e3fa17c003a92271f000a9a3aec253c094381f2fc80026f235918322cb358d53"

      def install
        bin.install "wd-go"
        fish_function.install "fish-support/wd.fish"
        (share/"fish/vendor_conf.d").install "fish-support/wd-go_on_prompt.fish"
        (prefix/"etc/profile.d").install "bash-zsh-support/wd.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/warpdrive-go/releases/download/v1.0.4/wd-go_1.0.4_Linux_arm64.tar.gz"
      sha256 "558f5b8c668d7974bcce8cc8e0a70b12702b020ed41455e263cf16ce654cf6c8"

      def install
        bin.install "wd-go"
        fish_function.install "fish-support/wd.fish"
        (share/"fish/vendor_conf.d").install "fish-support/wd-go_on_prompt.fish"
        (prefix/"etc/profile.d").install "bash-zsh-support/wd.sh"
      end
    end
  end

  def caveats
    <<~EOS
      For bash or zsh, put something like this in a profile file (like ~/.bash_profile or ~/.zshrc):
      . #{etc}/profile.d/wd.sh
    EOS
  end
end
