# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WdGo < Formula
  desc "Warp across the filesystem instantly"
  homepage "https://github.com/quackduck/warpdrive-go"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/warpdrive-go/releases/download/v1.0.5/wd-go_1.0.5_Darwin_x86_64.tar.gz"
      sha256 "f7f2e01bb123f17d714a7117e3ba8838a7f1e45ce795d8b1690853ac5a303f18"

      def install
        bin.install "wd-go"
        fish_function.install "fish-support/wd.fish"
        (share/"fish/vendor_conf.d").install "fish-support/wd-go_on_prompt.fish"
        (prefix/"etc/profile.d").install "bash-zsh-support/wd.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quackduck/warpdrive-go/releases/download/v1.0.5/wd-go_1.0.5_Darwin_arm64.tar.gz"
      sha256 "d704b28b5b92c27d7159d432191a31923991e0802039b7cb833eec243d14721a"

      def install
        bin.install "wd-go"
        fish_function.install "fish-support/wd.fish"
        (share/"fish/vendor_conf.d").install "fish-support/wd-go_on_prompt.fish"
        (prefix/"etc/profile.d").install "bash-zsh-support/wd.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/warpdrive-go/releases/download/v1.0.5/wd-go_1.0.5_Linux_armv6.tar.gz"
      sha256 "89870df4a10125fbfc999a8985316cba3595e3322be054af4b4d04249859c458"

      def install
        bin.install "wd-go"
        fish_function.install "fish-support/wd.fish"
        (share/"fish/vendor_conf.d").install "fish-support/wd-go_on_prompt.fish"
        (prefix/"etc/profile.d").install "bash-zsh-support/wd.sh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/warpdrive-go/releases/download/v1.0.5/wd-go_1.0.5_Linux_x86_64.tar.gz"
      sha256 "613dc20622f8f469bda6d1935d542850e533942059c887d2613bd3e904f476c0"

      def install
        bin.install "wd-go"
        fish_function.install "fish-support/wd.fish"
        (share/"fish/vendor_conf.d").install "fish-support/wd-go_on_prompt.fish"
        (prefix/"etc/profile.d").install "bash-zsh-support/wd.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quackduck/warpdrive-go/releases/download/v1.0.5/wd-go_1.0.5_Linux_arm64.tar.gz"
      sha256 "bbee89b40b16e18feb367f94c0a964ae713fdd851e7494be0abf508303ecce72"

      def install
        bin.install "wd-go"
        fish_function.install "fish-support/wd.fish"
        (share/"fish/vendor_conf.d").install "fish-support/wd-go_on_prompt.fish"
        (prefix/"etc/profile.d").install "bash-zsh-support/wd.sh"
      end
    end
  end

  def caveats
    <<~EOS
      For bash or zsh, put something like this in a profile file (like ~/.bash_profile or ~/.zshrc):
      . #{etc}/profile.d/wd.sh
    EOS
  end
end
