# This file was generated by GoReleaser. DO NOT EDIT.
class Uniclip < Formula
  desc "Cross-platform shared clipboard"
  homepage "https://github.com/quackduck/uniclip"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/quackduck/uniclip/releases/download/v1.0.1/uniclip_1.0.1_Darwin_x86_64.tar.gz"
    sha256 "27cf1ad8d5b4d7cdbc0f45dc6d7dfdbf86e14afa7c059df74f0211281e1a8ff1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/quackduck/uniclip/releases/download/v1.0.1/uniclip_1.0.1_Linux_x86_64.tar.gz"
      sha256 "cb3d85d0ae93d712a965ab2581c15b406604421dd970bd4228fb9a52d8c665db"
    end
  end

  def install
    bin.install "uniclip"
  end
end
